#!/usr/bin/env bash
# setup.sh — Guided first-time setup for a new machine or user account.
# Run this once: bash setup.sh
# It copies config templates, installs symlinks, and optionally switches to bash.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "======================================"
echo "  Dotfiles Setup"
echo "======================================"
echo ""

# ── 1. Profile ────────────────────────────────────────────────────────────────
echo "Which profile would you like?"
echo "  1) full     — everything (dev aliases, git power tools, completions) — macOS/Linux"
echo "  2) standard — git tools, custom prompt, venv scaffolding, machine-specific aliases"
echo "  3) minimal  — basics only (ls shortcuts, safety nets, simple git)"
echo ""
read -rp "Enter 1, 2, or 3 [default: 2]: " profile_choice
case "$profile_choice" in
  1) DOTFILES_PROFILE="full" ;;
  3) DOTFILES_PROFILE="minimal" ;;
  *) DOTFILES_PROFILE="standard" ;;
esac
echo "→ Profile: $DOTFILES_PROFILE"
echo ""

# ── 2. Username ───────────────────────────────────────────────────────────────
echo "What is your username on this machine?"
echo "  (This is just used to personalise the prompt. Press Enter to use: $USER)"
echo ""
read -rp "Username [$USER]: " input_username
LOCAL_USERNAME="${input_username:-$USER}"
echo "→ Username: $LOCAL_USERNAME"
echo ""

# ── 3. Write ~/.user_config ───────────────────────────────────────────────────
USER_CONFIG="$HOME/.user_config"
if [[ -f "$USER_CONFIG" ]]; then
  echo "~/.user_config already exists. Skipping (delete it to reconfigure)."
else
  cat > "$USER_CONFIG" <<EOF
# ~/.user_config — machine/user-specific settings, not committed to git
# Generated by setup.sh on $(date +%Y-%m-%d)

export LOCAL_USERNAME="$LOCAL_USERNAME"
export DOTFILES_PROFILE="$DOTFILES_PROFILE"
export DOTFILES_REPO="$SCRIPT_DIR"

# Uncomment and set if you have a code directory:
# export CODE_BASE="\$HOME/Code"
EOF
  echo "→ Created ~/.user_config"
fi
echo ""

# ── 4. Create ~/.local_aliases if missing ────────────────────────────────────
LOCAL_ALIASES="$HOME/.local_aliases"
if [[ -f "$LOCAL_ALIASES" ]]; then
  echo "~/.local_aliases already exists. Skipping."
else
  cp "$SCRIPT_DIR/.local_aliases_template" "$LOCAL_ALIASES"
  echo "→ Created ~/.local_aliases from template"
  echo "   Edit it later to set machine-specific paths."
fi
echo ""

# ── 5. Create ~/.venv_aliases_local if missing ───────────────────────────────
VENV_ALIASES="$HOME/.venv_aliases_local"
if [[ -f "$VENV_ALIASES" ]]; then
  echo "~/.venv_aliases_local already exists. Skipping."
else
  cp "$SCRIPT_DIR/.venv_aliases_local_template" "$VENV_ALIASES"
  echo "→ Created ~/.venv_aliases_local from template"
fi
echo ""

# ── 6. Run bootstrap (installs symlinks) ─────────────────────────────────────
echo "Installing dotfile symlinks..."
bash "$SCRIPT_DIR/bootstrap.sh"
echo ""

# ── 7. Git identity ───────────────────────────────────────────────────────────
echo "Checking Git identity..."
git_name=$(git config --global user.name 2>/dev/null || echo "")
git_email=$(git config --global user.email 2>/dev/null || echo "")

if [[ -n "$git_name" && -n "$git_email" ]]; then
  echo "Git identity already set:"
  echo "  Name:  $git_name"
  echo "  Email: $git_email"
  read -rp "Keep these? [Y/n]: " keep_git
  if [[ "$keep_git" =~ ^[Nn]$ ]]; then
    git_name=""
    git_email=""
  else
    echo "→ Keeping existing Git identity."
  fi
fi

if [[ -z "$git_name" || -z "$git_email" ]]; then
  echo "Git uses your name and email to label every commit you make."
  echo ""
  read -rp "Your full name (e.g. Jane Smith): " git_name_input
  read -rp "Your email address: " git_email_input
  if [[ -n "$git_name_input" && -n "$git_email_input" ]]; then
    git config --global user.name "$git_name_input"
    git config --global user.email "$git_email_input"
    git config --global init.defaultBranch main
    echo "→ Git identity set."
  else
    echo "→ Skipped. Set later with:"
    echo "   git config --global user.name 'Your Name'"
    echo "   git config --global user.email 'you@example.com'"
  fi
fi
echo ""

# ── 8. Optionally switch default shell to bash (macOS only) ──────────────────
if [[ "$(uname)" == "Darwin" ]]; then
  # Prefer Homebrew bash (5.x) if available; fall back to system bash (3.2)
  if [[ -x /opt/homebrew/bin/bash ]]; then
    SETUP_BASH=/opt/homebrew/bin/bash
  elif [[ -x /usr/local/bin/bash ]]; then
    SETUP_BASH=/usr/local/bin/bash
  else
    SETUP_BASH=/bin/bash
  fi

  current_shell="$(dscl . -read /Users/"$USER" UserShell 2>/dev/null | awk '{print $2}')"
  if [[ "$current_shell" != *bash* ]]; then
    echo "Your default shell is: $current_shell"
    echo "These dotfiles are written for bash."
    echo "Would you like to switch your default shell to bash?"
    read -rp "Switch to bash? [y/N]: " switch_shell
    if [[ "$switch_shell" =~ ^[Yy]$ ]]; then
      # Ensure the chosen bash is listed in /etc/shells before chsh
      if ! grep -qxF "$SETUP_BASH" /etc/shells 2>/dev/null; then
        echo "$SETUP_BASH" | sudo tee -a /etc/shells >/dev/null
      fi
      chsh -s "$SETUP_BASH" "$USER"
      echo "→ Default shell changed to $SETUP_BASH"
      echo "   Open a new terminal window for this to take effect."
    else
      echo "→ Keeping $current_shell. Note: .bash_profile will not load by default."
      echo "   You can change this later with: chsh -s $SETUP_BASH"
    fi
  else
    echo "→ Default shell is already bash. Good."
  fi
fi
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo "======================================"
echo "  Setup complete!"
echo "======================================"
echo ""
echo "Next steps:"
echo "  1. Open a new terminal (or run: source ~/.bash_profile)"
echo "  2. Run 'useful' to see available commands"
echo "  3. Read GUIDE.md in the repo for a full reference (Git, venv, SSH, aliases, and more)"
if [[ "$DOTFILES_PROFILE" != "minimal" ]]; then
  echo "  4. Edit ~/.local_aliases for machine-specific paths and aliases"
fi
echo ""
