#!/usr/bin/env bash
# setup.sh — Guided first-time setup for a new machine or user account.
# Run this once: bash setup.sh
# It copies config templates, installs symlinks, and optionally switches to bash.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "======================================"
echo "  Dotfiles Setup"
echo "======================================"
echo ""

# ── 1. Profile ────────────────────────────────────────────────────────────────
echo "Which profile would you like?"
echo "  1) full     — everything (dev aliases, WSL/Windows paths, git submodule tools)"
echo "  2) standard — git tools, custom prompt, venv scaffolding, machine-specific aliases"
echo "  3) minimal  — basics only (ls shortcuts, safety nets, simple git)"
echo ""
read -rp "Enter 1, 2, or 3 [default: 2]: " profile_choice
case "$profile_choice" in
  1) DOTFILES_PROFILE="full" ;;
  3) DOTFILES_PROFILE="minimal" ;;
  *) DOTFILES_PROFILE="standard" ;;
esac
echo "→ Profile: $DOTFILES_PROFILE"
echo ""

# ── 2. Username ───────────────────────────────────────────────────────────────
echo "What is your username on this machine?"
echo "  (This is just used to personalise the prompt. Press Enter to use: $USER)"
echo ""
read -rp "Username [$USER]: " input_username
LOCAL_USERNAME="${input_username:-$USER}"
echo "→ Username: $LOCAL_USERNAME"
echo ""

# ── 3. Write ~/.user_config ───────────────────────────────────────────────────
USER_CONFIG="$HOME/.user_config"
if [[ -f "$USER_CONFIG" ]]; then
  echo "~/.user_config already exists. Skipping (delete it to reconfigure)."
else
  cat > "$USER_CONFIG" <<EOF
# ~/.user_config — machine/user-specific settings, not committed to git
# Generated by setup.sh on $(date +%Y-%m-%d)

export LOCAL_USERNAME="$LOCAL_USERNAME"
export DOTFILES_PROFILE="$DOTFILES_PROFILE"
export DOTFILES_REPO="$SCRIPT_DIR"

# Uncomment and set if you have a code directory:
# export CODE_BASE="\$HOME/Code"
EOF
  echo "→ Created ~/.user_config"
fi
echo ""

# ── 4. Create ~/.local_aliases if missing ────────────────────────────────────
LOCAL_ALIASES="$HOME/.local_aliases"
if [[ -f "$LOCAL_ALIASES" ]]; then
  echo "~/.local_aliases already exists. Skipping."
else
  cp "$SCRIPT_DIR/.local_aliases_template" "$LOCAL_ALIASES"
  echo "→ Created ~/.local_aliases from template"
  echo "   Edit it later to set machine-specific paths."
fi
echo ""

# ── 5. Create ~/.venv_aliases_local if missing ───────────────────────────────
VENV_ALIASES="$HOME/.venv_aliases_local"
if [[ -f "$VENV_ALIASES" ]]; then
  echo "~/.venv_aliases_local already exists. Skipping."
else
  cp "$SCRIPT_DIR/.venv_aliases_local_template" "$VENV_ALIASES"
  echo "→ Created ~/.venv_aliases_local from template"
fi
echo ""

# ── 6. Run bootstrap (installs symlinks) ─────────────────────────────────────
echo "Installing dotfile symlinks..."
bash "$SCRIPT_DIR/bootstrap.sh"
echo ""

# ── 7. Optionally switch default shell to bash (macOS only) ──────────────────
if [[ "$(uname)" == "Darwin" ]]; then
  current_shell="$(dscl . -read /Users/"$USER" UserShell 2>/dev/null | awk '{print $2}')"
  if [[ "$current_shell" != *bash* ]]; then
    echo "Your default shell is: $current_shell"
    echo "These dotfiles are written for bash."
    echo "Would you like to switch your default shell to bash?"
    read -rp "Switch to bash? [y/N]: " switch_shell
    if [[ "$switch_shell" =~ ^[Yy]$ ]]; then
      chsh -s /bin/bash "$USER"
      echo "→ Default shell changed to /bin/bash"
      echo "   Open a new terminal window for this to take effect."
    else
      echo "→ Keeping $current_shell. Note: .bash_profile will not load by default."
      echo "   You can change this later with: chsh -s /bin/bash"
    fi
  else
    echo "→ Default shell is already bash. Good."
  fi
fi
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo "======================================"
echo "  Setup complete!"
echo "======================================"
echo ""
echo "Next steps:"
echo "  1. Open a new terminal (or run: source ~/.bash_profile)"
echo "  2. Run 'useful' or 'more_useful' to see available commands"
if [[ "$DOTFILES_PROFILE" == "minimal" ]]; then
echo "  3. Your profile is 'minimal' — clean and simple. Run 'useful' for a command list."
elif [[ "$DOTFILES_PROFILE" == "standard" ]]; then
echo "  3. Your profile is 'standard' — run 'useful' for a command list. Edit ~/.local_aliases for machine-specific paths."
else
echo "  3. Your profile is 'full' — edit ~/.local_aliases for machine-specific paths."
fi
echo ""
